TARGET_VIMRC=$HOME/.vimrc
TARGET_NVIMRC=$HOME/.config/nvim/init.vim
TARGET_VIM_HOME_FOLDER=$HOME/.vim
TARGET_NVIM_HOME_FOLDER=$HOME/.nvim

rm $TARGET_VIMRC
rm $TARGET_NVIMRC
rm -rf $TARGET_VIM_HOME_FOLDER
rm -rf $TARGET_NVIM_HOME_FOLDER

